# SPDX-FileCopyrightText: 2014, microg Project Team
# SPDX-License-Identifier: CC0-1.0

language: android
sudo: false
before_script:
  - echo sdk.dir $ANDROID_HOME > local.properties
script:
  - jdk_switcher use oraclejdk8
  - export TERM=dumb
  - export JAVA_OPTS="-XX:+CMSClassUnloadingEnabled -XX:+HeapDumpOnOutOfMemoryError -Xmx2048m"
  - ./gradlew build
android:
  components:
  - tools
  - platform-tools
  - build-tools-29.0.3
  - android-29
  - extra-android-m2repository
